version: '3'

networks:
  laravel:

services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
  # Database
  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: vending-machine
      MYSQL_USER: techtest
      MYSQL_PASSWORD: strongP@5%
      MYSQL_ROOT_PASSWORD: strongP@5%
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
